config/routes.rb
Rails.application.routes.draw do
  
  #Redirections
  get '/admin', to: redirect('/admins/sign_in')
  
  # Devise routes
  devise_for :admins, controllers: { sessions: "sessions/admin" }
  devise_for :users,  controllers: { sessions: "sessions/user", registrations: "registrations/user" }
  
  # Admin routes
  namespace :admin, shallow: true do
    resources :categories do
      get 'status', on: :member
      resources :groups do
        resources :enrollments do
          resources :payments
        end
      end
    end
    resources :all_payments do
      get 'status', on: :member
    end
    resources :users
  end
  
  # Public routes
  resources :organizations, only: [:index], shallow: true do
    resources :categories do
      resources :groups do
        resources :enrollments, only: [:new, :create]
      end
    end
  end
  
  # Private routes
  resources :enrollments, except: [:new, :create], shallow: true do
    resources :payments
  end
  
  root "organizations#index"
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :enrollment
  
  default_scope { order(date: :desc) }
end

app/controllers/admin/payments_controller.rb
class Admin::PaymentsController < Admin::AdminController
  before_action :set_enrollment, only: [:index, :new, :create]
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  def index
    @payments = @enrollment.payments.all
  end

  def show
  end

  def new
    @payment = Payment.new
  end

  def edit
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.enrollment = @enrollment

    respond_to do |format|
      if @payment.save
        format.html { redirect_to enrollment_payments_path(@enrollment), notice: 'Pago reportado' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to admin_enrollment_payments_path(@payment.enrollment), notice: 'Pago actualizado' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to admin_enrollment_payments_url(@payment.enrollment), notice: 'Pago eliminado' }
      format.json { head :no_content }
    end
  end

  private
    def set_enrollment
      @enrollment = Enrollment.find(params[:enrollment_id])
      redirect_to admin_categories_url, notice: 'Acceso no permitido' if @enrollment.group.category.organization != @org
    end
    
    def set_payment
      @payment = Payment.find(params[:id])
      redirect_to admin_categories_url, notice: 'Acceso no permitido' if @payment.enrollment.group.category.organization != @org
    end
    
    def payment_params
      params.require(:payment).permit(:amount, :status, :date, :bank, :reference, :owner, :concept, :comments, :enrollment_id)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_enrollment, only: [:index, :new, :create]
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  def index
    @payments = @enrollment.payments.all
  end

  def show
  end

  def new
    @payment = Payment.new
  end

  def edit
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.enrollment = @enrollment
    @payment.status = 0

    if @payment.save
      redirect_to enrollment_payments_path(@enrollment), notice: 'Pago reportado'
    else
      render :new
    end
  end

  def update
    if @payment.update(payment_params)
      redirect_to enrollment_payments_path(@payment.enrollment), notice: 'Pago actualizado'
    else
      render :edit
    end
  end

  def destroy
    @payment.destroy
    redirect_to enrollment_payments_url(@payment.enrollment), notice: 'Pago eliminado'
  end

  private
    def set_enrollment
      @enrollment = Enrollment.find(params[:enrollment_id])
      redirect_to enrollments_url, notice: 'Acceso no permitido' if @enrollment.user != current_user
    end
    
    def set_payment
      @payment = Payment.find(params[:id])
      redirect_to enrollments_url, notice: 'Acceso no permitido' if @payment.enrollment.user != current_user
    end

    def payment_params
      params.require(:payment).permit(:amount, :status, :date, :bank, :reference, :owner, :concept, :comments, :enrollment_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for([@enrollment, @payment]) do |f| %>
  
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label>Monto de Pago</label>
        <%= f.number_field :amount, class: "form-control", required: true %>
      </div>  
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>Fecha de Pago</label>
        <%= f.date_field :date, class: "form-control", required: true %>
      </div>  
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>Concepto de Pago</label>
        <%= f.text_field :concept, class: "form-control", required: true %>
      </div>  
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label>Banco de Origen</label>
        <%= f.text_field :bank, class: "form-control", required: true %>
      </div>  
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>Referencia de Pago</label>
        <%= f.text_field :reference, class: "form-control", required: true %>
      </div>  
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>Titular de Cuenta</label>
        <%= f.text_field :owner, class: "form-control"%>
      </div>  
    </div>
  </div>

  <%= f.submit "REPORTAR MI PAGO", class: "btn btn-block btn-info btn-fill" %>
  <div class="clearfix"></div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', enrollment_payments_path(@payment.enrollment) %>

app/views/payments/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header text-center">
            <div class="row">
              <div class="col-md-2 hidden-xs">
                <%= link_to enrollments_path, class: "btn btn-info" do %>
                  <i class="fa fa-arrow-left"></i> Regresar
                <% end %>
              </div>
              <div class="col-md-8">
                <h4 class="title">Mis Pagos</h4>
                <p class="category"><%= @enrollment.group.name %></p>
              </div>
              <div class="col-md-2">
                <%= link_to 'Nuevo Pago', new_enrollment_payment_path(@enrollment), class: "btn btn-info btn-block btn-fill btn-lg" %>
              </div>
            </div>
          </div>
          <hr>
          <div class="content">
            <div class="fresh-datatables">
              <table class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                <thead>
                  <tr>
                    <th>Fecha</th>
                    <th>Concepto</th>
                    <th>Monto</th>
                    <th>Referencia</th>
                    <th>Status</th>
                    <th class="disabled-sorting text-right">Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  <% @payments.each do |payment| %>
                    <tr>
                      <td><%= payment.date %></td>
                      <td><%= payment.concept %></td>
                      <td><%= number_with_delimiter payment.amount, locale: :es %></td>
                      <td><%= payment.reference %></td>
                      <% if payment.status == 1 %>
                          <td><button class="btn btn-sm btn-success btn-fill">Confirmado</button></td>
                        <% else %>
                          <td><button class="btn btn-sm btn-warning btn-fill">Por Confirmar</button></td>
                        <% end %>
                      <td class="text-right">
                        <%= link_to payment, method: :delete, data: { confirm: '¿Estás seguro que deseas borrar este pago?' }, class: "btn btn-simple btn-danger btn-icon remove" do %>
                          <i class="fa fa-times"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div><!-- end content-->
        </div><!--  end card  -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>

        </div>

app/views/payments/new.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header text-center">
            <div class="row">
              <div class="col-md-2 hidden-xs">
                <%= link_to enrollment_payments_path(@enrollment), class: "btn btn-info" do %>
                  <i class="fa fa-arrow-left"></i> Regresar</a>
                <% end %>
              </div>
              <div class="col-md-8">
                <h4 class="title">Nuevo Pago</h4>
                <p class="category"><%= @enrollment.group.name %></p>
              </div>
              <div class="col-md-2">
              </div>
            </div>
          </div>
          <hr>
          <div class="content">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @payment.date %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @payment.bank %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @payment.reference %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @payment.owner %>
</p>

<p>
  <strong>Concept:</strong>
  <%= @payment.concept %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @payment.comments %>
</p>

<p>
  <strong>Enrollment:</strong>
  <%= @payment.enrollment %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>