config/routes.rb
Rails.application.routes.draw do
  
  #Redirections
  get '/admin', to: redirect('/admins/sign_in')
  
  # Devise routes
  devise_for :admins, controllers: { sessions: "sessions/admin" }
  devise_for :users,  controllers: { sessions: "sessions/user", registrations: "registrations/user" }
  
  # Admin routes
  namespace :admin, shallow: true do
    resources :categories do
      get 'status', on: :member
      resources :groups do
        resources :enrollments do
          resources :payments
        end
      end
    end
    resources :all_payments do
      get 'status', on: :member
    end
    resources :users
  end
  
  # Public routes
  resources :organizations, only: [:index], shallow: true do
    resources :categories do
      resources :groups do
        resources :enrollments, only: [:new, :create]
      end
    end
  end
  
  # Private routes
  resources :enrollments, except: [:new, :create], shallow: true do
    resources :payments
  end
  
  root "organizations#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :organization
  has_many :groups, dependent: :destroy
  
  validates :name, :position, presence: true
  validates :name, uniqueness: { scope: :organization,
    message: "debe ser única por organización" }
  validates :position, numericality: {greater_than_or_equal_to: 1}
  
  default_scope { order(position: :asc) }
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_categories, only: [:index, :new, :edit]
  before_action :set_category,   only: [:show, :edit, :update, :destroy, :status]

  def index
  end

  def show
  end
  
  def status
    @category.toggle :status
    @category.save
    @categories = @org.categories
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @categories = @org.categories.where("position >= ?", params[:category][:position]).to_a
    @category = Category.new(category_params)
    @category.organization = @org

    respond_to do |format|
      if @category.save
        @categories.each do |category|
          category.increment!(:position)
        end
        format.html { redirect_to admin_categories_path, notice: "Categoría #{@category.name.titleize} creada" }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    new_position = params[:category][:position].to_i
    old_position = @category.position.to_i
    if new_position < old_position
      @categories = @org.categories.where(position: new_position..old_position-1).to_a
    elsif new_position > old_position
      @categories = @org.categories.where(position: old_position+1..new_position).to_a
    end
    if @category.update(category_params)
      if new_position < old_position
        @categories.each do |category|
          category.increment!(:position)
        end
      elsif new_position > old_position
        @categories.each do |category|
          category.decrement!(:position)
        end
      end
      redirect_to admin_categories_path, notice: "Categoría #{@category.name.titleize} actualizada"
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    @categories = @org.categories.where("position >= ?", @category.position)
    @categories.each do |category|
      category.decrement!(:position)
    end
    redirect_to admin_categories_url, notice: "Categoría #{@category.name.titleize} eliminada"
  end

  private
    def set_categories
      @categories = @org.categories
    end
    
    def set_category
      @category = Category.find(params[:id])
      redirect_to admin_categories_url, notice: 'Acceso no permitido' if @category.organization != @org
    end

    def category_params
      params.require(:category).permit(:position, :name, :status, :organization_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_organization, only: [:index, :new, :create]
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  def index
    @categories = @organization.categories.where(status: true)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_organization
      session[:org] = params[:organization_id]
      @organization = Organization.find(params[:organization_id])
    end
    
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:position, :name, :status, :organization_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<% @categories.each do |category| %>
  <tr>
    <td><%= category.position %></td>
    <td><%= category.name %></td>
    <% if category.status %>
      <td><%= link_to "Activa", status_admin_category_path(category), remote: true, class: "btn btn-sm btn-success btn-fill" %></td>
    <% else %>
      <td><%= link_to "Inactiva", status_admin_category_path(category), remote: true, class: "btn btn-sm btn-warning btn-fill" %></td>
    <% end %>
    <td>
      <%= link_to admin_category_groups_path(category), class: "btn btn-sm btn-info btn-fill" do %>
         Ver <%= category.groups.count %>
      <% end %>
    </td>
    <td class=" text-right">
      <%= link_to edit_admin_category_path(category), class: "btn btn-simple btn-warning btn-icon edit" do %>
        <i class="fa fa-edit"></i>
      <% end %>
      <%= link_to admin_category_path(category), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-simple btn-danger btn-icon remove" do %>
        <i class="fa fa-times"></i>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <label>Nombre</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Nombre de la Categoría" %>
  </div>
  <div class="form-group">
    <label>Posición</label>
    <%= f.select :position, options_for_select(1..@categories.count+1, selected: @category.position), {}, {class: 'selectpicker'} %>
  </div>
  <div class="form-group">
    <label>Status</label>
    <%= f.select :status, options_for_select([["Activo", true],["Inactivo", false]], selected: @category.status), {}, {class: 'selectpicker'} %>
  </div>
  <br>
  <%= f.submit "Guardar", class: "btn btn-block btn-fill btn-info" %>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header">
            Editar Categoría
            <%= link_to admin_categories_path, class: "btn btn-info pull-right" do %>
              <i class="fa fa-arrow-left"></i> Regresar</a>
            <% end %>
          </div>
          <div class="content">
            <%= render 'form' %>
          </div>
        </div> <!-- end card -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="content">
              <div class="toolbar">
                <%= link_to new_admin_category_path, class: "btn btn-fill btn-info" do %>
                  <i class="fa fa-plus"></i> Nueva Categoría
                <% end %>
              </div>
              <div class="fresh-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                  <thead>
                  <tr>
                    <th>Posición</th>
                    <th>Categoría</th>
                    <th>Status</th>
                    <th>Grupos</th>
                    <th class="disabled-sorting text-right">Actions</th>
                  </tr>
                  </thead>
                  <tbody id="all-categories">
                    <%= render "category" %>
                  </tbody>
                </table>
              </div>
          </div><!-- end content-->
        </div><!--  end card  -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header">
            Nueva Categoría
            <%= link_to admin_categories_path, class: "btn btn-info pull-right" do %>
              <i class="fa fa-arrow-left"></i> Regresar</a>
            <% end %>
          </div>
          <div class="content">
            <%= render 'form' %>
          </div>
        </div> <!-- end card -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>
</div>

app/views/admin/categories/status.js.erb
$("#all-categories").html("<%= escape_javascript(render 'category') %>");