config/routes.rb
Rails.application.routes.draw do
  
  #Redirections
  get '/admin', to: redirect('/admins/sign_in')
  
  # Devise routes
  devise_for :admins, controllers: { sessions: "sessions/admin" }
  devise_for :users,  controllers: { sessions: "sessions/user", registrations: "registrations/user" }
  
  # Admin routes
  namespace :admin, shallow: true do
    resources :categories do
      get 'status', on: :member
      resources :groups do
        resources :enrollments do
          resources :payments
        end
      end
    end
    resources :all_payments do
      get 'status', on: :member
    end
    resources :users
  end
  
  # Public routes
  resources :organizations, only: [:index], shallow: true do
    resources :categories do
      resources :groups do
        resources :enrollments, only: [:new, :create]
      end
    end
  end
  
  # Private routes
  resources :enrollments, except: [:new, :create], shallow: true do
    resources :payments
  end
  
  root "organizations#index"
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :category
  has_many   :enrollments, dependent: :destroy
  
  default_scope { order(position: :asc) }
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::AdminController
  before_action :set_category,      only: [:index, :new, :create]
  before_action :set_group,         only: [:show, :edit, :update, :destroy]
  before_action :set_groups_count,  only: [:new, :edit]

  def index
    @groups = @category.groups
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @groups = @category.groups.where("position >= ?", params[:group][:position]).to_a
    @group = Group.new(group_params)
    @group.category = @category

    respond_to do |format|
      if @group.save
        @groups.each do |group|
          group.increment!(:position)
        end
        format.html { redirect_to admin_category_groups_path(@category), notice: "#{@group.name.titleize} creado" }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    new_position = params[:group][:position].to_i
    old_position = @group.position.to_i
    if new_position < old_position
      @groups = @group.category.groups.where(position: new_position..old_position-1).to_a
    elsif new_position > old_position
      @groups = @group.category.groups.where(position: old_position+1..new_position).to_a
    end
    if @group.update(group_params)
      if new_position < old_position
        @groups.each do |group|
          group.increment!(:position)
        end
      elsif new_position > old_position
        @groups.each do |group|
          group.decrement!(:position)
        end
      end
      redirect_to admin_category_groups_path(@group.category), notice: "#{@group.name.titleize} actualizado"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    @groups = @group.category.groups.where("position >= ?", @group.position)
    @groups.each do |group|
      group.decrement!(:position)
    end
    redirect_to admin_category_groups_url(@group.category), notice: "#{@group.name.titleize} eliminado"
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
      redirect_to admin_categories_url, notice: 'Acceso no permitido' if @category.organization != @org
    end
    
    def set_groups_count
      if @category
        @groups_count = @category.groups.count
      else
        @groups_count = @group.category.groups.count
      end
    end
    
    def set_group
      @group = Group.find(params[:id])
      redirect_to admin_categories_url, notice: 'Acceso no permitido' if @group.category.organization != @org
    end

    def group_params
      params.require(:group).permit(:position, :name, :description, :places, :status, :category_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_category, only: [:index, :new, :create]
  before_action :set_group,    only: [:show, :edit, :update, :destroy]

  def index
    @groups = @category.groups.where(status: true)
  end

  def show
    @available_places = @group.places - @group.enrollments.count
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end
    
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:position, :name, :description, :places, :status, :category_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/admin/groups/_form.html.erb
<%= form_for([:admin, @category, @group]) do |f| %>
  
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <label>Nombre</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Nombre del Grupo", required: true %>
  </div>
  <div class="form-group">
    <label>Cupos</label>
    <%= f.number_field :places, class: "form-control", placeholder: "Total cupos disponibles", required: true %>
  </div>
  <div class="form-group">
    <label>Posición</label>
    <%= f.select :position, options_for_select(1..@groups_count+1, selected: @group.position), {}, {class: 'selectpicker'} %>
  </div>
  <div class="form-group">
    <label>Status</label>
    <%= f.select :status, options_for_select([["Activo", true],["Inactivo", false]], selected: @group.status), {}, {class: 'selectpicker'} %>
  </div>
  <div class="form-group">
    <label>Descripción</label>
    <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Descripción del Grupo" %>
  </div>
  <br>
  <%= f.submit "Guardar", class: "btn btn-block btn-fill btn-info" %>
<% end %>

app/views/admin/groups/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header">
            Editar Grupo
            <%= link_to admin_category_groups_path(@group.category), class: "btn btn-info pull-right" do %>
              <i class="fa fa-arrow-left"></i> Regresar</a>
            <% end %>
          </div>
          <div class="content">
            <%= render 'form' %>
          </div>
        </div> <!-- end card -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>
</div>

app/views/admin/groups/index.html.erb
<% content_for :breadcrumb do %>
  <%= link_to "Grupos en #{@category.name}", admin_categories_path, class: "navbar-brand" %>
<% end %>

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="content">
              <div class="toolbar">
                <%= link_to new_admin_category_group_path(@category), class: "btn btn-fill btn-info" do %>
                  <i class="fa fa-plus"></i> Nuevo Grupo
                <% end %>
              </div>
              <div class="fresh-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                  <thead>
                  <tr>
                    <th>Posición</th>
                    <th>Grupo</th>
                    <th>Status</th>
                    <th>Inscritos</th>
                    <th class="disabled-sorting text-right">Acciones</th>
                  </tr>
                  </thead>
                  <tbody>
                    <% @groups.each do |group| %>
                      <tr>
                        <td><%= group.position %></td>
                        <td><%= group.name %></td>
                        <% if group.status %>
                          <td><button class="btn btn-sm btn-success btn-fill">Activo</button></td>
                        <% else %>
                          <td><button class="btn btn-sm btn-warning btn-fill">Inactivo</button></td>
                        <% end %>
                        <td>
                          <%= link_to admin_group_enrollments_path(group), class: "btn btn-sm btn-info btn-fill" do %>
                             <%= group.enrollments.count %> de <%= group.places %>
                          <% end %>
                        </td>
                        <td class=" text-right">
                          <%= link_to edit_admin_group_path(group), class: "btn btn-simple btn-warning btn-icon edit" do %>
                            <i class="fa fa-edit"></i>
                          <% end %>
                          <%= link_to admin_group_path(group), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-simple btn-danger btn-icon remove" do %>
                            <i class="fa fa-times"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
          </div><!-- end content-->
        </div><!--  end card  -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>
</div>

app/views/admin/groups/new.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header">
            Nuevo Grupo
            <%= link_to admin_category_groups_path(@category), class: "btn btn-info pull-right" do %>
              <i class="fa fa-arrow-left"></i> Regresar</a>
            <% end %>
          </div>
          <div class="content">
            <%= render 'form' %>
          </div>
        </div> <!-- end card -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>
</div>

app/views/admin/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @group.position %>
</p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Places:</strong>
  <%= @group.places %>
</p>

<p>
  <strong>Status:</strong>
  <%= @group.status %>
</p>

<p>
  <strong>Category:</strong>
  <%= @group.category %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>