config/routes.rb
Rails.application.routes.draw do
  
  #Redirections
  get '/admin', to: redirect('/admins/sign_in')
  
  # Devise routes
  devise_for :admins, controllers: { sessions: "sessions/admin" }
  devise_for :users,  controllers: { sessions: "sessions/user", registrations: "registrations/user" }
  
  # Admin routes
  namespace :admin, shallow: true do
    resources :categories do
      get 'status', on: :member
      resources :groups do
        resources :enrollments do
          resources :payments
        end
      end
    end
    resources :all_payments do
      get 'status', on: :member
    end
    resources :users
  end
  
  # Public routes
  resources :organizations, only: [:index], shallow: true do
    resources :categories do
      resources :groups do
        resources :enrollments, only: [:new, :create]
      end
    end
  end
  
  # Private routes
  resources :enrollments, except: [:new, :create], shallow: true do
    resources :payments
  end
  
  root "organizations#index"
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_many :payments, dependent: :destroy
  
  accepts_nested_attributes_for :payments, allow_destroy: true
  
  default_scope { order(first_name: :asc) }
  
  def full_name
    [first_name, last_name].select(&:present?).join(' ').titleize
  end
end

app/controllers/admin/enrollments_controller.rb
class Admin::EnrollmentsController < Admin::AdminController
  before_action :set_group,      only: [:index, :new, :create]
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  def index
    @enrollments = @group.enrollments
  end

  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to admin_group_enrollments_path(@enrollment.group), notice: 'Inscripción actualizada' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Inscripción eliminada' }
      format.json { head :no_content }
    end
  end

  private
    def set_group
      @group = Group.find(params[:group_id])
      redirect_to admin_categories_url, notice: 'Acceso no permitido' if @group.category.organization != @org
    end
    
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
      redirect_to admin_categories_url, notice: 'Acceso no permitido' if @enrollment.group.category.organization != @org
    end

    def enrollment_params
      params.require(:enrollment).permit(
        :first_name, :last_name, :birthdate, :status, :id_number, :email, :phone, :mobile, :address,
        :occupation, :refered_by, :comments, payments_attributes: 
        [ :id, :amount, :status, :date, :bank, :reference, :owner, :concept, :comments ])
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:new, :create]
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  def index
    @enrollments = current_user.enrollments
  end

  def show
  end

  def new
    @enrollment = Enrollment.new
    @enrollment.payments.build
  end

  def edit
  end

  def create
    @enrollment = Enrollment.new(enrollment_params)
    @enrollment.user  = current_user
    @enrollment.group = @group
    @enrollment.status = 0

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollments_path, notice: "Te has inscrito en #{@enrollment.group.name.titleize}" }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_group
      @group = Group.find(params[:group_id])
    end
    
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    def enrollment_params
      params.require(:enrollment).permit(
        :first_name, :last_name, :birthdate, :status, :id_number, :email, :phone, :mobile, :address,
        :occupation, :refered_by, :comments, payments_attributes: 
        [ :id, :amount, :status, :date, :bank, :reference, :owner, :concept, :comments ])
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/admin/enrollments/_form.html.erb
<%= form_for([:admin, @group, @enrollment]) do |f| %>
  
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label>Status</label>
        <%= f.select :status, options_for_select([["Confirmada", 1],["Por Confirmar", 0]], selected: @enrollment.status), {}, {class: 'selectpicker'} %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <label>Nombres</label>
        <%= f.text_field :first_name, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label>Apellidos</label>
        <%= f.text_field :last_name, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label>Fecha de Nacimiento</label>
        <%= f.date_field :birthdate, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-3">
      <% unless @enrollment.group.category.organization.id == 4 %>
      <div class="form-group">
        <label>Cedula</label>
        <%= f.text_field :id_number, class: "form-control", required: true %>
      </div>
      <% end %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <label>Teléfono</label>
        <%= f.text_field :phone, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label>Celular</label>
        <%= f.text_field :mobile, class: "form-control", required: true %>
      </div>
    </div>
    <% unless @enrollment.group.category.organization.id == 4 %>
    <div class="col-md-3">
      <div class="form-group">
        <label>Ocupación</label>
        <%= f.text_field :occupation, class: "form-control", required: true %>
      </div>
    </div>
    <% end %>
    <div class="col-md-3">
      <div class="form-group">
        <label>¿Quién lo refirió?</label>
        <%= f.text_field :refered_by, class: "form-control", required: true %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for="adresse-field">Dirección Domicilio</label>
            <%= f.text_area :address, class: "form-control", required: true %>
        </div>
    </div>
  </div>
  
  <div class="header text-center">Pago de inscripción</div></br>
  
  <%= f.fields_for :payments do |fp| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label>Monto de Pago</label>
        <%= fp.number_field :amount, class: "form-control", required: true %>
      </div>  
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>Fecha de Pago</label>
        <%= fp.date_field :date, class: "form-control", required: true %>
      </div>  
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label>Concepto de Pago</label>
        <%= fp.text_field :concept, class: "form-control", required: true %>
      </div>  
    </div>
  </div>
  
  <div class="row">
    <% unless @enrollment.group.category.organization.id == 4 %>
    <div class="col-md-4">
      <div class="form-group">
        <label>Banco de Origen</label>
        <%= fp.text_field :bank, class: "form-control", required: true %>
      </div>  
    </div>
    <% end %>
    <div class="col-md-4">
      <div class="form-group">
        <label>Referencia de Pago</label>
        <%= fp.text_field :reference, class: "form-control", required: true %>
      </div>  
    </div>
    <% unless @enrollment.group.category.organization.id == 4 %>
    <div class="col-md-4">
      <div class="form-group">
        <label>Titular de Cuenta</label>
        <%= fp.text_field :owner, class: "form-control"%>
      </div>  
    </div>
    <% end %>
  </div>
  <% end %>

  <%= f.submit "REGISTRAR MI INSCRIPCIÓN", class: "btn btn-block btn-info btn-fill" %>
  <div class="clearfix"></div>
<% end %>

app/views/admin/enrollments/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header">
            Editar Inscripción
            <%= link_to admin_group_enrollments_path(@enrollment.group), class: "btn btn-info pull-right" do %>
              <i class="fa fa-arrow-left"></i> Regresar</a>
            <% end %>
          </div>
          <div class="content">
            <%= render 'form' %>
          </div>
        </div> <!-- end card -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>
</div>

app/views/admin/enrollments/index.html.erb
<% content_for :breadcrumb do %>
  <%= link_to "Inscritos en #{@group.name}", admin_category_groups_path(@group.category), class: "navbar-brand" %>
<% end %>

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="content">
              <div class="toolbar">
                <%= link_to admin_category_groups_path(@group.category), class: "btn btn-info" do %>
                  <i class="fa fa-arrow-left"></i> Regresar</a>
                <% end %>
              </div>
              <div class="fresh-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                  <thead>
                  <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Email</th>
                    <th>Teléfono</th>
                    <th>Status</th>
                    <th>Pagos</th>
                    <th class="disabled-sorting text-right">Acciones</th>
                  </tr>
                  </thead>
                  <tbody>
                    <% @enrollments.each do |enrollment| %>
                      <tr>
                        <td><%= enrollment.first_name %></td>
                        <td><%= enrollment.last_name %></td>
                        <td><%= enrollment.user.email %></td>
                        <td><%= enrollment.mobile %></td>
                        <% if enrollment.status == 1 %>
                          <td><button class="btn btn-sm btn-success btn-fill">Confirmada</button></td>
                        <% else %>
                          <td><button class="btn btn-sm btn-warning btn-fill">Por Confirmar</button></td>
                        <% end %>
                        <td>
                          <%= link_to admin_enrollment_payments_path(enrollment), class: "btn btn-sm btn-info btn-fill" do %>
                             <%= enrollment.payments.count %>
                          <% end %>
                        </td>
                        <td class=" text-right">
                          <%= link_to edit_admin_enrollment_path(enrollment), class: "btn btn-simple btn-warning btn-icon edit" do %>
                            <i class="fa fa-edit"></i>
                          <% end %>
                          <%= link_to admin_enrollment_path(enrollment), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-simple btn-danger btn-icon remove" do %>
                            <i class="fa fa-times"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
          </div><!-- end content-->
        </div><!--  end card  -->
      </div> <!-- end col-md-12 -->
    </div> <!-- end row -->
  </div>
</div>

app/views/admin/enrollments/new.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header text-center">
            <div class="row">
              <div class="col-md-2 hidden-xs">
                <%= link_to group_path(@group), class: "btn btn-info" do %>
                  <i class="fa fa-arrow-left"></i> Regresar</a>
                <% end %>
              </div>
              <div class="col-md-8">
                <h4 class="title">Inscripcion: <%= @group.name %></h4>
              </div>
              <div class="col-md-2">
              </div>
            </div>
          </div>
          <hr>
          <div class="content">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @enrollment.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @enrollment.last_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @enrollment.status %>
</p>

<p>
  <strong>Id number:</strong>
  <%= @enrollment.id_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enrollment.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @enrollment.phone %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @enrollment.occupation %>
</p>

<p>
  <strong>Refered by:</strong>
  <%= @enrollment.refered_by %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @enrollment.comments %>
</p>

<p>
  <strong>Group:</strong>
  <%= @enrollment.group %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>